import type { EventCard } from '../types';

// Debt-repudiation blowback events. Each is gated on its repudiation flag, so
// the "slightly more disruption chances" only exist after the player chooses
// to default. Paris repudiation has NO events here by design — its price is
// purely financial (loan windows shut, leverage -8, trust -4).
export const DEBT_EVENTS: EventCard[] = [
  {
    id: 'event_debt_coast_fuel_sabotage',
    titleAr: 'تخريب خطوط الفيول في الساحل رداً على التنصل من الديون الروسية',
    category: 'SECURITY',
    sourceAr: 'إدارة مرفأ طرطوس / شبكات متعهدي المحروقات الساحلية',
    descriptionAr: 'تعرضت صهاريج الفيول وخطوط الإمداد بين بانياس وطرطوس لأعمال تخريب متزامنة، وتتهم التحقيقات شبكات متعهدين كانت تعتاش على العقود الروسية وتضررت من إعلان التنصل.',
    targetGovernorateId: 'latakia',
    triggerCondition: (state) =>
      (state.flags?.Debt_Repudiated_Russia ?? 0) === 1 && state.turnNumber >= 3,
    options: [
      {
        id: 'opt_coast_hush_contracts',
        labelAr: 'احتواء الشبكات بعقود بديلة وتمويل إصلاح عاجل',
        descriptionAr: 'دفع تعويضات وإعادة تأهيل الخطوط عبر متعهدين محليين موالين لامتصاص الغضب الساحلي.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $20M',
        canChoose: true,
        costUSD: 20_000_000,
        costSYP: 0,
        costPC: 6,
        effectTrust: 2,
        effectRRI: -4,
        effectCorruption: 2,
        effectCompetence: 0,
        customEffectAr: 'تهدئة الساحل: -8 احتقان باللاذقية وطرطوس',
        governorateEffects: [
          { governorateId: 'latakia', prri: -8, customSummaryAr: 'إصلاح الخطوط الساحلية (-8 احتقان)' },
          { governorateId: 'tartus', prri: -8, customSummaryAr: 'عقود بديلة لمتعهدي المرفأ (-8 احتقان)' },
        ],
      },
      {
        id: 'opt_coast_security_sweep',
        labelAr: 'حملة أمنية واسعة ضد شبكات التخريب',
        descriptionAr: 'مداهمات واعتقالات في أوساط المتعهدين والمشغلين المرتبطين بالعقود الروسية السابقة.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 12',
        canChoose: true,
        costUSD: 0,
        costSYP: 400_000_000_000,
        costPC: 12,
        effectTrust: -6,
        effectRRI: 6,
        effectCorruption: -3,
        effectCompetence: 0,
        customEffectAr: 'ردع الشبكات بالقوة: -10 احتقان ساحلي مقابل +6 احتقان وطني',
        governorateEffects: [
          { governorateId: 'latakia', prri: -10, sectarianAnxiety: 6, customSummaryAr: 'كسر شبكات التخريب (-10 احتقان، +6 قلق طائفي)' },
          { governorateId: 'tartus', prri: -10, sectarianAnxiety: 6, customSummaryAr: 'تأمين المرفأ بالقوة (-10 احتقان، +6 قلق طائفي)' },
        ],
      },
      {
        id: 'opt_coast_endure_blackout',
        labelAr: 'تحمل الانقطاعات وإصلاح الخطوط بالقدرات الذاتية',
        descriptionAr: 'ترك الورش المحلية تصلح الأضرار ببطء دون إنفاق سيادي إضافي.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -4,
        effectRRI: 8,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'تفاقم الغضب الساحلي: +10 احتقان و+2 ساعات تقنين',
        governorateEffects: [
          { governorateId: 'latakia', prri: 10, dailyBlackoutHours: 2, customSummaryAr: 'انقطاعات ممتدة (+10 احتقان)' },
          { governorateId: 'tartus', prri: 10, dailyBlackoutHours: 2, customSummaryAr: 'شلل جزئي بالمرفأ (+10 احتقان)' },
        ],
      },
    ],
  },
  {
    id: 'event_debt_suwayda_contraband_surge',
    titleAr: 'طفرة التهريب في الجنوب بعد وقف القسط النفطي الإيراني',
    category: 'SOUTHERN',
    sourceAr: 'وجهاء جبل العرب / قيادة شرطة درعا',
    descriptionAr: 'ملأت شبكات التهريب المرتبطة بخطوط الإمداد الإيرانية السابقة الفراغ برفع تهريب المحروقات عبر البادية، مبتزة التجار ووجهاء الجبل معاً.',
    targetGovernorateId: 'as_suwayda',
    triggerCondition: (state) =>
      (state.flags?.Debt_Repudiated_Iran_Formal ?? 0) === 1 && state.turnNumber >= 3,
    options: [
      {
        id: 'opt_suwayda_buy_calm',
        labelAr: 'شراء الهدوء بمخصصات وقود إضافية للجبل',
        descriptionAr: 'ضخ محروقات مدعومة للسويداء عبر القنوات الرسمية لقطع الطريق على المهربين.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $15M',
        canChoose: true,
        costUSD: 15_000_000,
        costSYP: 0,
        costPC: 6,
        effectTrust: 3,
        effectRRI: -5,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'تهدئة الجبل: -8 احتقان و-6 احتمال انفصال',
        governorateEffects: [
          { governorateId: 'as_suwayda', prri: -8, suwaydaSecessionProb: -6, customSummaryAr: 'وقود رسمي يقطع سوق المهربين' },
        ],
      },
      {
        id: 'opt_suwayda_border_crackdown',
        labelAr: 'حملة ضبط للمعابر الصحراوية ومصادرة الصهاريج',
        descriptionAr: 'نشر سرايا الهجانة على خطوط التهريب ومصادرة الشاحنات والصهاريج المخالفة.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 10',
        canChoose: true,
        costUSD: 0,
        costSYP: 300_000_000_000,
        costPC: 10,
        effectTrust: -4,
        effectRRI: 5,
        effectCorruption: -2,
        effectCompetence: 0,
        customEffectAr: 'كسر الشبكات: -10 احتقان لكن +8 غضب عشائري',
        governorateEffects: [
          { governorateId: 'as_suwayda', prri: -10, tribalRageIndex: 8, customSummaryAr: 'مصادرة الصهاريج (-10 احتقان، +8 غضب)' },
        ],
      },
      {
        id: 'opt_suwayda_look_away',
        labelAr: 'غض الطرف مؤقتاً عن شبكات التهريب',
        descriptionAr: 'ترك السوق السوداء تمتص الصدمة دون تدخل سيادي مباشر.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -3,
        effectRRI: 7,
        effectCorruption: 6,
        effectCompetence: 0,
        customEffectAr: 'تمدد الشبكات: +10 احتقان و+8 احتمال انفصال',
        governorateEffects: [
          { governorateId: 'as_suwayda', prri: 10, suwaydaSecessionProb: 8, customSummaryAr: 'المهربون يملأون الفراغ السيادي' },
        ],
      },
    ],
  },
  {
    id: 'event_debt_hasakah_oil_wheat_squeeze',
    titleAr: 'ابتزاز نفطي وقمحي في الجزيرة بعد التنصل من طهران',
    category: 'SECURITY',
    sourceAr: 'مديرية الحبوب بالحسكة / إدارة حقول رميلان',
    descriptionAr: 'استغلت شبكات مرتبطة بخطوط التمويل الإيرانية السابقة أزمة التنصل لرفع أسعار نقل القمح وتعطيل ضخ النفط من حقول الجزيرة نحو مصافي حمص.',
    targetGovernorateId: 'hasakeh',
    triggerCondition: (state) =>
      (state.flags?.Debt_Repudiated_Iran_Formal ?? 0) === 1 && state.turnNumber >= 4,
    options: [
      {
        id: 'opt_hasakah_cash_flow',
        labelAr: 'الدفع النقدي المباشر لضمان تدفق القمح والنفط',
        descriptionAr: 'شراء الولاء اللوجستي نقداً: دفع فوري لمتعهدي النقل ومشغلي الحقول.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $18M',
        canChoose: true,
        costUSD: 18_000_000,
        costSYP: 0,
        costPC: 5,
        effectTrust: 2,
        effectRRI: -5,
        effectCorruption: 3,
        effectCompetence: 0,
        customEffectAr: 'تأمين الإمدادات: -8 احتقان بالحسكة ودير الزور',
        governorateEffects: [
          { governorateId: 'hasakeh', prri: -8, tribalRageIndex: -6, customSummaryAr: 'تأمين قمح الجزيرة ونفطها' },
          { governorateId: 'deir_ez_zor', prri: -8, tribalRageIndex: -6, customSummaryAr: 'فتح ممرات النقل الشرقية' },
        ],
      },
      {
        id: 'opt_hasakah_tribal_pact',
        labelAr: 'ميثاق عشائري لتأمين الحقول والصوامع',
        descriptionAr: 'تفويض شيوخ العشائر حماية المنشآت مقابل اعتراف رسمي بنفوذهم المحلي.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 8',
        canChoose: true,
        costUSD: 0,
        costSYP: 200_000_000_000,
        costPC: 8,
        effectTrust: 1,
        effectRRI: -3,
        effectCorruption: 4,
        effectCompetence: -2,
        customEffectAr: 'حماية عشائرية: -6 احتقان مقابل +10 غضب قبلي لاحق',
        governorateEffects: [
          { governorateId: 'hasakeh', prri: -6, tribalRageIndex: 10, customSummaryAr: 'العشائر تحرس الحقول بشروطها' },
          { governorateId: 'deir_ez_zor', prri: -6, tribalRageIndex: 10, customSummaryAr: 'نفوذ عشائري موسع على المعابر' },
        ],
      },
      {
        id: 'opt_hasakah_absorb_shock',
        labelAr: 'امتصاص الصدمة وانتظار انكسار المضاربين',
        descriptionAr: 'تحمل شح الوقود والقمح دوراً كاملاً بانتظار انهيار أسعار السوق السوداء.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -5,
        effectRRI: 9,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'أزمة إمداد: +10 احتقان و+2 تقنين',
        governorateEffects: [
          { governorateId: 'hasakeh', prri: 10, dailyBlackoutHours: 2, customSummaryAr: 'شح الوقود والقمح معاً' },
          { governorateId: 'deir_ez_zor', prri: 10, dailyBlackoutHours: 2, customSummaryAr: 'توقف ضخ النفط للغرب' },
        ],
      },
    ],
  },
];
