import type { EventCard } from '../types';

export const MASTER_EVENTS: EventCard[] = [
  {
    id: 'event_01_grain_corridor',
    titleAr: 'انهيار ممر الحبوب في البحر الأسود',
    category: 'EXOGENOUS',
    sourceAr: 'منظمة الأغذية والزراعة (فاو) / وزارة الاقتصاد',
    descriptionAr: 'توقفت حركة شحن القمح والذرة عبر البحر الأسود إثر اشتعال النزاع الإقليمي، ما تسبب في قفزة فورية لأسعار القمح الطري بنسبة 48% في البورصات العالمية، ويهدد مخزون الخبز الاستراتيجي في البلاد.',
    options: [
      {
        id: 'opt_absorb',
        labelAr: 'التحمل المالي الكامل (تغطية فارق السعر)',
        descriptionAr: 'شراء شحنات القمح بالأسعار العالمية الجديدة من الاحتياطي للحفاظ على وزن وجودة ربطة الخبز المدعومة.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $180M',
        canChoose: true,
        costUSD: 180_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 4,
        effectRRI: -6,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'استقرار أسواق الخبز وتهدئة الشارع (+4 ثقة مدنية)',
      },
      {
        id: 'opt_ration',
        labelAr: 'تقنين الدقيق وتخفيض مخصصات الأفران (الدقيق الأصفر)',
        descriptionAr: 'خلط دقيق القمح بالذرة الصفراء وتقليص وزن ربطة الخبز بمقدار 25% لتوفير النقد الأجنبي.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 55_000_000,
        costSYP: 12_000_000_000,
        costPC: 0,
        effectTrust: -14,
        effectRRI: 18,
        effectCorruption: 6,
        effectCompetence: 0,
        customEffectAr: 'ازدحام طوابير الخبز واشتعال الغضب الشعبي (+18 احتقان)',
      },
      {
        id: 'opt_swap',
        labelAr: 'مبادلة قمح عبر خط ائتماني شرقي بشروط امتيازية',
        descriptionAr: 'توقيع اتفاقية استيراد قمح طويلة الأجل مع شريك استراتيجي مقابل منح امتيازات استثمارية في ميناء طرطوس.',
        requirementsDescriptionAr: 'مؤشر السيادة والاستقلال >= 30',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 15,
        effectTrust: -2,
        effectRRI: -2,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'زيادة الدين الخارجي بمقدار $290M وتراجع مؤشر السيادة (-15)',
      },
    ],
  },
  {
    id: 'event_02_tanker_interdiction',
    titleAr: 'اعتراض ناقلة النفط في البحر الأبيض المتوسط',
    category: 'EXOGENOUS',
    sourceAr: 'مكتب المخابرات البحرية / مصفاة بانياس',
    descriptionAr: 'تم احتجاز ناقلة نفط خام محملة بـ 1.5 مليون برميل كانت في طريقها لتشغيل مصفاة بانياس وتأمين وقود المازوت للتدفئة، ما يهدد بانهيار ساعات التغذية الكهربائية إلى ساعة ونصف يومياً.',
    options: [
      {
        id: 'opt_land_smuggle',
        labelAr: 'تأمين خط إمداد بري بديل للشاحنات عبر الحدود',
        descriptionAr: 'الاعتماد على شبكات التجار لنقل صهاريج المازوت براً عبر ممرات إقليمية بتكلفة نقدية محلية باهظة.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 25',
        canChoose: true,
        costUSD: 0,
        costSYP: 28_000_000_000,
        costPC: 25,
        effectTrust: -5,
        effectRRI: 6,
        effectCorruption: 12,
        effectCompetence: -4,
        customEffectAr: 'تزايد سطوة مافيات التهريب والعمولات (+12 فساد بنيوي)',
      },
      {
        id: 'opt_curtail',
        labelAr: 'تقنين قاسٍ واستنزاف المخزون الاحتياطي للأفران والمشافي',
        descriptionAr: 'قطع تزويد المصانع والمركبات العامة بالوقود وحصره في المشافي وصوامع الحبوب فقط.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -22,
        effectRRI: 26,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'شلل في قطاع المواصلات وتراجع الإنتاج الصناعي بنسبة -35%',
      },
      {
        id: 'opt_spot_buy',
        labelAr: 'شراء شحنة فورية طارئة من السوق المفتوحة بالدولار',
        descriptionAr: 'دفع علاوة مخاطر مرتفعة لشركات شحن خاصة لتفريغ حمولة نفط فورية في ميناء طرطوس.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $140M',
        canChoose: true,
        costUSD: 140_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 3,
        effectRRI: -4,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'استقرار جزئي للمصافي وحماية ساعات التغذية الكهربائية',
      },
    ],
  },
  {
    id: 'event_03_beirut_banking',
    titleAr: 'تجميد الودائع المصرفية في بيروت',
    category: 'ENDOGENOUS',
    sourceAr: 'المصرف المركزي / غرفة تجارة دمشق وحلب',
    descriptionAr: 'أعلنت المصارف اللبنانية تعليق السحوبات الخارجية للشركات السورية، ما جمد أكثر من 1.2 مليار دولار من خطوط الائتمان العائدة لكبار التجار، ويهدد بانهيار سعر صرف SP بالسوق الموازي.',
    options: [
      {
        id: 'opt_decree_54',
        labelAr: 'تجريم حيازة وتداول العملات الأجنبية (المرسوم 54)',
        descriptionAr: 'إطلاق حملة أمنية على شركات الصرافة لمنع تسرب SP خارج المصارف الرسمية.',
        requirementsDescriptionAr: 'كفاءة وزارة المالية >= 45',
        canChoose: true,
        costUSD: 0,
        costSYP: 3_000_000_000,
        costPC: 20,
        effectTrust: -15,
        effectRRI: 12,
        effectCorruption: 8,
        effectCompetence: 0,
        customEffectAr: 'تراجع الحوالات الخارجية بنسبة 60% وهروب السيولة إلى الخارج',
      },
      {
        id: 'opt_align_rate',
        labelAr: 'تحرير مرن للسعر الرسمي ومجاراة سعر السوق',
        descriptionAr: 'تعديل سعر المصرف المركزي ليقترب من سعر السوق، لجذب حوالات المغتربين عبر القنوات الرسمية.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 10,
        effectTrust: 5,
        effectRRI: 4,
        effectCorruption: -6,
        effectCompetence: 6,
        customEffectAr: 'استقطاب الحوالات رسمياً (+40%) مع موجة تضخم استهلاكي قصيرة',
      },
    ],
  },
  {
    id: 'event_04_latakia_standoff',
    titleAr: 'تمرد إدارة محطة الحاويات بمرفأ اللاذقية',
    category: 'ENDOGENOUS',
    sourceAr: 'هيئة الجمارك العامة / أمن الموانئ',
    descriptionAr: 'رفضت إدارة محطة الحاويات الخاضعة لنفوذ أحد حيتان التجارة السابقين توريد عوائد الرسوم الجمركية البالغة 85 مليون دولار للخزينة العامة، محتمية بشبكات مسلحة محلية في الساحل.',
    options: [
      {
        id: 'opt_raid_port',
        labelAr: 'إرسال قوات الأمن المركزي لبسط السيطرة بالقوة',
        descriptionAr: 'اقتحام إدارة المرفأ ومصادرة الحسابات بالقوة وفرض سلطة الخزينة العامة المركزية.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 40',
        canChoose: true,
        costUSD: -85_000_000, // NET GAIN (Captured cash)
        costSYP: 15_000_000_000,
        costPC: 40,
        effectTrust: 8,
        effectRRI: -4,
        effectCorruption: -12,
        effectCompetence: 6,
        customEffectAr: 'استرداد $85M نقداً وتطهير الميناء مع توتر أمني مؤقت بالساحل',
      },
      {
        id: 'opt_compromise_port',
        labelAr: 'تسوية ودية والحصول على حصة 35% من العوائد',
        descriptionAr: 'التنازل عن المحاسبة القضائية مقابل تحويل فوري لمبلغ 30 مليون دولار للخزينة.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: -30_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: -14,
        effectRRI: 8,
        effectCorruption: 10,
        effectCompetence: -8,
        customEffectAr: 'تعزيز إفلات النخب الفاسدة من العقاب وتكريس الفساد المؤسسي',
      },
    ],
  },
  {
    id: 'event_05_bab_el_mandeb',
    titleAr: 'أزمة الملاحة البحرية في باب المندب',
    category: 'EXOGENOUS',
    sourceAr: 'غرفة الملاحة البحرية ووزارة الاقتصاد',
    descriptionAr: 'أجبرت الهجمات البحرية في مضيق باب المندب كبرى خطوط الشحن على تحويل مسار سفنها حول رأس الرجاء الصالح، ما أخر وصول البضائع إلى الساحل السوري 22 يوماً ورفع كلفة الحاويات 260%.',
    options: [
      {
        id: 'opt_freight_subsidize',
        labelAr: 'تحمل الخزينة لفوارق رسوم الشحن والتأمين البحري',
        descriptionAr: 'دفع دعم سيادي مباشر لشركات الشحن لحماية خطوط إمداد المصانع بالأوليات وضبط الأسعار.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $95M',
        canChoose: true,
        costUSD: 95_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 3,
        effectRRI: -4,
        effectCorruption: 0,
        effectCompetence: 4,
        customEffectAr: 'استقرار أسعار السلع وحماية مصانع حلب وعدرا من الإغلاق',
      },
      {
        id: 'opt_freight_laissez',
        labelAr: 'تحرير التكلفة بالكامل وتحميلها للمستهلك النهائي',
        descriptionAr: 'ترك الأسعار تخضع لقوى العرض والطلب دون إنفاق أي دولار من الاحتياطي.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -18,
        effectRRI: 12,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'موجة غلاء تضخمية عاتية (+18%) وتوقف 24% من الورش الصناعية',
      },
      {
        id: 'opt_freight_overland',
        labelAr: 'التحول للشحن البري عبر موانئ الخليج والأردن',
        descriptionAr: 'تفريغ الحاويات في الموانئ الخليجية ونقلها بالشاحنات عبر معبر نصيب الحدودي.',
        requirementsDescriptionAr: 'كفاءة وزارة الاقتصاد >= 40',
        canChoose: true,
        costUSD: 0,
        costSYP: 14_000_000_000,
        costPC: 20,
        effectTrust: 2,
        effectRRI: -2,
        effectCorruption: 4,
        effectCompetence: 8,
        customEffectAr: 'اختصار زمن التوريد بمقدار 8 أيام وتنشيط تجارة الترانزيت بنصيب',
      },
    ],
  },
  {
    id: 'event_06_hormuz_interdiction',
    titleAr: 'اعتراض إمدادات الطاقة في مضيق هرمز',
    category: 'EXOGENOUS',
    sourceAr: 'وزارة الطاقة / شركة محروقات',
    descriptionAr: 'أدى التصعيد العسكري في الخليج إلى قفزة بأسعار خام برنت العالمية بنسبة 32%، وامتناع شركات التأمين الدولية عن تغطية ناقلات الوقود المتجهة لشرق المتوسط دون أقساط حرب قياسية.',
    options: [
      {
        id: 'opt_hormuz_guarantee',
        labelAr: 'تغطية أقساط التأمين ضد مخاطر الحرب سيادياً بالدولار',
        descriptionAr: 'تحمل الخزينة لأقساط التأمين الفورية لضمان استمرار وصول ناقلات الفيول والغاز لمصافي البلاد.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $160M',
        canChoose: true,
        costUSD: 160_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 4,
        effectRRI: -5,
        effectCorruption: 0,
        effectCompetence: 4,
        customEffectAr: 'حماية محطات التوليد ومصافي النفط من التوقف المفاجئ',
      },
      {
        id: 'opt_hormuz_shedding',
        labelAr: 'تقنين كهربائي حاد وتخفيض التوليد إلى 1,200 ميغاواط',
        descriptionAr: 'الحفاظ على الدولار عبر إطفاء محطات التوليد في حلب والوسط وتوزيع الكهرباء لساعتين يومياً.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -20,
        effectRRI: 24,
        effectCorruption: 0,
        effectCompetence: 0,
        customEffectAr: 'ظلام دامس في معظم المدن وارتفاع تكلفة أجور النقل بنسبة 140%',
      },
    ],
  },
  {
    id: 'event_07_euphrates_flow',
    titleAr: 'انحسار تدفق مياه نهر الفرات',
    category: 'EXOGENOUS',
    sourceAr: 'إدارة سد الطبقة / وزارة الموارد المائية',
    descriptionAr: 'تراجع منسوب المياه المتدفقة في نهر الفرات بنسبة 60% نتيجة الجفاف والسدود الإقليمية في المنبع، ما هبط ببحيرة الطبقة تحت مستوى توربينات التوليد الكهرومائي وهدد مئات آلاف الهكتارات المروية بالبوار.',
    options: [
      {
        id: 'opt_thermal_switch',
        labelAr: 'تشغيل محطات التوليد الحرارية وتخصيص المياه للزراعة',
        descriptionAr: 'تعويض نقص الطاقة الكهرومائية بشراء فيول حراري إضافي بالدولار لحماية قنوات ري قمح الجزيرة.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $110M',
        canChoose: true,
        costUSD: 110_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 4,
        effectRRI: -4,
        effectCorruption: 0,
        effectCompetence: 6,
        customEffectAr: 'إنقاذ محصول القمح الاستراتيجي في حوض الفرات والجزيرة',
      },
      {
        id: 'opt_deplete_reservoir',
        labelAr: 'استنزاف المخزون الميت لبحيرة السد لتشغيل العنفات',
        descriptionAr: 'توليد الكهرباء لأقصى حد لثلاثة أشهر ثم المخاطرة بجفاف كامل للقنوات الزراعية لاحقاً.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 0,
        effectTrust: -15,
        effectRRI: 14,
        effectCorruption: 0,
        effectCompetence: -8,
        customEffectAr: 'بوار 350,000 هكتار زراعي وموجة نزوح بيئي واسعة من الريف الشرقي',
      },
    ],
  },
  {
    id: 'event_08_aleppo_turbine',
    titleAr: 'انفجار العنفة البخارية في محطة حلب الحرارية',
    category: 'ENDOGENOUS',
    sourceAr: 'الشركة العامة للكهرباء بحلب / وزارة الطاقة',
    descriptionAr: 'تعرضت المجموعة البخارية الرئيسية بقدرة 400 ميغاواط في محطة حلب الحرارية لانفجار ناجم عن سوء الصيانة وحرق الفيول الثقيل، ما قطع الكهرباء بالكامل عن مدينة الشيخ نجار الصناعية.',
    options: [
      {
        id: 'opt_oem_repair',
        labelAr: 'عقد صيانة دولي طارئ مع الشركة المصنعة (OEM)',
        descriptionAr: 'استقدام طواقم هندسية وتوريد قطع غيار أصلية لضمان إعادة تشغيل العنفة بقدرتها الكاملة.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $175M',
        canChoose: true,
        costUSD: 175_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 8,
        effectRRI: -6,
        effectCorruption: -4,
        effectCompetence: 10,
        customEffectAr: 'إعادة 400 ميغاواط نظيفة للشبكة ورفع كفاءة وزارة الطاقة',
      },
      {
        id: 'opt_scrap_patch',
        labelAr: 'ترقيع العنفة بجهود محلية واستخدام قطع خردة مستهلكة',
        descriptionAr: 'إجراء صيانة بدائية محلياً دون استنزاف رصيد الدولار، مع المخاطرة بانفجار متكرر.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 4_500_000_000,
        costPC: 0,
        effectTrust: -8,
        effectRRI: 10,
        effectCorruption: 4,
        effectCompetence: -6,
        customEffectAr: 'تشغيل جزئي بكفاءة 45% فقط مع خطر دائم لتعطل المحطة مجدداً',
      },
    ],
  },
  {
    id: 'event_09_gas_severance',
    titleAr: 'انقطاع إمدادات الغاز الطبيعي لمحطات التوليد',
    category: 'ENDOGENOUS',
    sourceAr: 'الشركة السورية للغاز / محطة دير علي',
    descriptionAr: 'أدى تعطل ضواغط الغاز في البادية وتراكم مستحقات الصيانة إلى انقطاع 6.5 مليون متر مكعب يومياً من الغاز الجاف، ما يهدد بإطفاء محطتي دير علي وجندر اللتين تغذيان دمشق والجنوب.',
    options: [
      {
        id: 'opt_settle_gas',
        labelAr: 'سداد ديون الصيانة واستيراد ضواغط توربينية حديثة',
        descriptionAr: 'دفع التكاليف بالدولار لإعادة ضخ الغاز وحماية 1,100 ميغاواط من التوليد النظيف.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $135M',
        canChoose: true,
        costUSD: 135_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 6,
        effectRRI: -8,
        effectCorruption: 0,
        effectCompetence: 6,
        customEffectAr: 'استقرار كهرباء العاصمة والجنوب السوري وتفادي إطفاء الشبكة',
      },
      {
        id: 'opt_switch_heavy_oil',
        labelAr: 'التحويل القسري لحرق الفيول الثقيل (المازوت)',
        descriptionAr: 'تشغيل محطات الغاز بالفيول والمازوت لتوفير الدولار، مع تدمير العمر الافتراضي للعنفات.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 40_000_000,
        costSYP: 18_000_000_000,
        costPC: 0,
        effectTrust: -6,
        effectRRI: 8,
        effectCorruption: 6,
        effectCompetence: -4,
        customEffectAr: 'انبعاثات سامة وتراجع كفاءة العنفات بنسبة 40% على المدى المتوسط',
      },
    ],
  },
  {
    id: 'event_10_medical_resignation',
    titleAr: 'موجة استقالات أطباء المشافي الحكومية',
    category: 'ENDOGENOUS',
    sourceAr: 'نقابة الأطباء / مشفى المواساة الجامعي',
    descriptionAr: 'قدم أكثر من 60% من أطباء الجراحة وأعضاء الهيئة التدريسية استقالاتهم احتجاجاً على تآكل الرواتب الحكومية إلى ما دون 25 دولاراً شهرياً، وتوجههم للهجرة نحو دول الخليج وأوروبا.',
    options: [
      {
        id: 'opt_dollar_stipend',
        labelAr: 'صرف حوافز شهرية خاصة للأطباء والكوادر الطبية بالدولار',
        descriptionAr: 'تخصيص صندوق نقد أجنبي لحماية الكفاءات الطبية وضمان استمرار المشافي المجانية.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $45M',
        canChoose: true,
        costUSD: 45_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 8,
        effectRRI: -4,
        effectCorruption: 0,
        effectCompetence: 8,
        customEffectAr: 'وقف نزيف الأطباء واستمرار عمل 85% من غرف العمليات الجراحية',
      },
      {
        id: 'opt_travel_ban',
        labelAr: 'منع السفر وإلزام الأطباء بخدمة مدنية إلزامية مشددة',
        descriptionAr: 'استخدام القوانين الأمنية لمنع سفر الكوادر الطبية دون زيادة في الرواتب.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 30',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 30,
        effectTrust: -20,
        effectRRI: 14,
        effectCorruption: 10,
        effectCompetence: -15,
        customEffectAr: 'تصاعد الهروب غير الشرعي وانهيار جودة الرعاية الطبية في المشافي',
      },
    ],
  },
  {
    id: 'event_11_poultry_feed_shock',
    titleAr: 'أزمة أعلاف الدواجن وذبح الدجاج البياض',
    category: 'ENDOGENOUS',
    sourceAr: 'اتحاد غرف الزراعة / مربو الدواجن في حماة وحمص',
    descriptionAr: 'قفزت أسعار الذرة الصفراء وفول الصويا المستوردين بنسبة 55%، ولجأ 60% من مربي الدواجن إلى ذبح قطعانهم لعدم قدرتهم على إطعامها وتدفئة المداجن في ظل انقطاع الكهرباء والمازوت.',
    options: [
      {
        id: 'opt_import_frozen',
        labelAr: 'فتح باب الاستيراد الفوري للفروج المجمد الرخيص بالدولار',
        descriptionAr: 'إغراق الأسواق بالفروج المجمد لحماية القدرة الشرائية للفقراء وتخفيض أسعار البروتين.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $75M',
        canChoose: true,
        costUSD: 75_000_000,
        costSYP: 0,
        costPC: 0,
        effectTrust: 2,
        effectRRI: -8,
        effectCorruption: 0,
        effectCompetence: 4,
        customEffectAr: 'انخفاض أسعار الفروج للمواطنين ولكن مع إفلاس 80% من المداجن المحلية',
      },
      {
        id: 'opt_subsidize_feed',
        labelAr: 'دعم حكومي مباشر لمستوردي وموزعي الأعلاف بـSP',
        descriptionAr: 'تحمل الخزينة لفارق سعر العلف لحماية المداجن المحلية وضمان استمرار إنتاج البيض واللحوم.',
        requirementsDescriptionAr: 'الخزينة العامة >= 35B SP',
        canChoose: true,
        costUSD: 0,
        costSYP: 35_000_000_000,
        costPC: 0,
        effectTrust: 6,
        effectRRI: -4,
        effectCorruption: 8,
        effectCompetence: 4,
        customEffectAr: 'حماية 70% من المداجن الوطنية مع تسرب بعض الأعلاف للسوق السوداء',
      },
    ],
  },
  {
    id: 'event_12_awassi_export',
    titleAr: 'جدل تصدير خراف العواس السورية وتهريبها',
    category: 'ENDOGENOUS',
    sourceAr: 'وزارة الزراعة / مربو الماشية في البادية',
    descriptionAr: 'أدى الطلب الخليجي الهائل على خراف العواس السورية إلى وصول سعر الرأس لـ 350 دولاراً، ما شجع عمليات تهريب واسعة عبر الحدود وأدى لارتفاع سعر كيلو لحم العواس بالمدن لـ 1,800 SP.',
    options: [
      {
        id: 'opt_ban_exports',
        labelAr: 'الحظر الصارم لتصدير الأغنام وملاحقة المهربين أمنياً',
        descriptionAr: 'منع خروج أي رأس غنم لإجبار المربين على البيع بالسوق المحلية وخفض أسعار اللحوم.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 25',
        canChoose: true,
        costUSD: 0,
        costSYP: 8_000_000_000,
        costPC: 25,
        effectTrust: 6,
        effectRRI: -4,
        effectCorruption: 6,
        effectCompetence: 2,
        customEffectAr: 'انخفاض أسعار اللحوم 40% بالمدن مع تذمر واسع بين مربي الماشية',
      },
      {
        id: 'opt_protein_swap',
        labelAr: 'بروتوكول مقايضة البروتين (تصدير العواس واستيراد البقر المجمد)',
        descriptionAr: 'السماح بتصدير حصص مقننة لجني الدولار، واستخدام جزء من العوائد لاستيراد لحوم مجمدة رخيصة.',
        requirementsDescriptionAr: 'احتياطي نقد أجنبي >= $60M',
        canChoose: true,
        costUSD: -20_000_000, // NET POSITIVE USD
        costSYP: 0,
        costPC: 15,
        effectTrust: 4,
        effectRRI: -2,
        effectCorruption: -2,
        effectCompetence: 8,
        customEffectAr: 'جني $20M صافي أرباح للخزينة وتأمين بروتين رخيص للطبقات الفقيرة',
      },
    ],
  },
];
