import type { EventCard } from '../types';

export const SOUTHERN_EVENTS: EventCard[] = [
  {
    id: 'event_s01_lajat_siege',
    titleAr: 'حصار منطقة اللجاة وقطع أوتوستراد دمشق - السويداء',
    category: 'SOUTHERN',
    sourceAr: 'قيادة شرطة درعا / وجهاء قبائل البادية',
    descriptionAr: 'قامت مجموعات عشائرية مسلحة من بدو اللجاة بقطع أوتوستراد دمشق-السويداء واحتجاز صهاريج الوقود والشاحنات، رداً على مصادرة أراضيهم وتهجير عائلاتهم خلال النزاعات السابقة مع فصائل السويداء المحلية.',
    options: [
      {
        id: 'opt_historic_accord',
        labelAr: 'وفاق الجنوب التاريخي (تعويض البدو + انتخابات بلدية بالسويداء)',
        descriptionAr: 'دفع تعويضات مالية سيادية لعائلات البدو المهجرة، مقابل فتح الأوتوستراد واعتراف فصائل السويداء بالسلطة المركزية.',
        requirementsDescriptionAr: 'الخزينة العامة >= 2.2 تريليون ل.س | رأس مال سياسي >= 30',
        canChoose: true,
        costUSD: 0,
        costSYP: 2_200_000_000_000,
        costPC: 30,
        effectTrust: 12,
        effectRRI: -8,
        effectCorruption: -6,
        effectCompetence: 8,
        customEffectAr: 'تحقيق الوفاق التاريخي: خفض مؤشر الانفصال بالسويداء وغضب القبائل إلى الصفر',
      },
      {
        id: 'opt_disarm_suwayda',
        labelAr: 'تجريد فصائل السويداء من السلاح بالقوة النظامية',
        descriptionAr: 'شن حملة عسكرية واسعة لكسر الفصائل المحلية ونزع سلاحها لإرضاء القبائل وبسط السيطرة.',
        requirementsDescriptionAr: 'رأس مال سياسي >= 45',
        canChoose: true,
        costUSD: 35_000_000,
        costSYP: 3_800_000_000_000,
        costPC: 45,
        effectTrust: -18,
        effectRRI: 28,
        effectCorruption: 10,
        effectCompetence: -5,
        customEffectAr: 'اشتعال تمرد مسلح شامل في جبل العرب وقفز مؤشر الانفصال لـ 95%',
      },
      {
        id: 'opt_arm_tribes',
        labelAr: 'تسليح المجموعات العشائرية لموازنة فصائل الجبل',
        descriptionAr: 'منح السلاح والملاذ للقبائل لمحاصرة السويداء وإنهاك الفصائل المحلية دون تدخل مباشر من الجيش.',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 1_100_000_000_000,
        costPC: 15,
        effectTrust: -16,
        effectRRI: 22,
        effectCorruption: 14,
        effectCompetence: -10,
        customEffectAr: 'اشتعال حرب أهلية طائفية في الجنوب وتوقف تام لحركة التجارة بمعبر نصيب',
      },
    ],
  },
  {
    id: 'event_d02_golan_incursion',
    titleAr: 'توغل عسكري في المنطقة العازلة بهضبة الجولان',
    category: 'SOUTHERN',
    sourceAr: 'شعبة الاستخبارات العسكرية / قيادة المنطقة الجنوبية',
    descriptionAr: 'توغلت دوريات عسكرية خارجية مدعومة بالجرافات داخل المنطقة العازلة في ريف القنيطرة الغربي، وأقامت سواتر ترابية وأبراج مراقبة متقدمة تطل على بلدات ريف درعا، ما أثار حالة ذعر واستنفار شعبي واسع.',
    options: [
      {
        id: 'opt_frozen_defense',
        labelAr: 'تثبيت خط دفاعي مجمد ونشر حرس الحدود (تكلفة استنزاف دفاعية)',
        descriptionAr: 'نشر وحدات مدربة لمنع أي تقدم إضافي وتجنب التصعيد الشامل، مع تخصيص موازنة دفاعية سنوية مستمرة.',
        requirementsDescriptionAr: 'الخزينة العامة >= 1.6 تريليون ل.س',
        canChoose: true,
        costUSD: 0,
        costSYP: 1_600_000_000_000,
        costPC: 15,
        effectTrust: 8,
        effectRRI: -4,
        effectCorruption: 0,
        effectCompetence: 6,
        customEffectAr: 'تثبيت خط المواجهة بصفته "نزاعاً مجمداً" دون تفجر حرب إقليمية واسعة',
      },
      {
        id: 'opt_diplomatic_un',
        labelAr: 'الرد الدبلوماسي وتقديم شكوى عاجلة لمجلس الأمن والأندوف',
        descriptionAr: 'تجنب أي انتشار عسكري والاعتماد على الوساطة الدولية وقوات الأمم المتحدة (UNDOF).',
        requirementsDescriptionAr: 'لا توجد متطلبات',
        canChoose: true,
        costUSD: 0,
        costSYP: 0,
        costPC: 5,
        effectTrust: -20,
        effectRRI: 18,
        effectCorruption: 0,
        effectCompetence: -6,
        customEffectAr: 'اتساع التوغل الخارجي وتصاعد الغضب الشعبي في درعا ضد عجز الحكومة',
      },
    ],
  },
];
