import type { GovernorateNode, MinistryProfile, CommissionState, ConfiscatedAsset, ForeignLoanPackage, SovereignMortgageOption } from './types';

export const INITIAL_YEAR = 2027;
export const MAX_TURNS = 40;

// Dual-Currency Macroeconomic Turn 1 Baselines
export const BASELINE_MACRO = {
  treasurySYP: 4_200_000_000_000,       // 4.20 Trillion SYP liquid cash
  reservesUSD: 320_000_000,             // $320M FX liquid reserves (~2.4 months import cover)
  m2MoneySupplySYP: 18_500_000_000_000, // 18.5 Trillion SYP domestic M2 money supply
  officialRateSYP: 13_500,              // Central Bank official peg
  parallelRateSYP: 16_200,              // Free-market parallel street FX rate
  monthlyFoodBasketSYP: 1_900_000,      // Minimum Expenditure Basket (MEB) for 5-person family
  civilServiceWageSYP: 405_000,         // Base civil servant monthly wage ($25.00/mo)
  annualInflationPct: 24.5,             // Annualized CPI inflation
  sovereignDebtUSD: 6_800_000_000,      // Pre-existing external debt
  sovereignLeverage: 65,                // 0 - 100 (National autonomy)
  politicalCapital: 50,                 // 0 - 100 (Presidential decree resource)
  civicTrust: 42,                       // 0 - 100 (Public confidence)
  systemicCorruption: 58,               // 0 - 100 (Institutional leakage drag)
  nationalRRI: 45,                      // 0 - 100 (National Riot Risk Index)
  gridCapacityMW: 2_250,                // Operational power (demand: 8,500 MW)
  dailyPowerHours: 3.5,                 // Average daily electricity
  taxCompliancePct: 35,                 // 0 - 100 (Dynamic fiscal compliance)
  civilServiceHeadcount: 1_400_000,     // Total active public & security personnel
};

// 14 Syrian Governorates Baseline Spatial & Economic Profile (UN OCHA HNO 2025-2026 & World Bank Data)
// Relative Hexagonal Grid: (Q, R) coordinates arranged geographically
export const BASELINE_GOVERNORATES: Record<string, GovernorateNode> = {
  aleppo: {
    id: 'aleppo',
    nameAr: 'حلب',
    archetype: 'revolution_hub',
    hexQ: 0,
    hexR: -2,
    population: 4_749_350,
    hostPopulation: 3_046_710,
    idpPopulation: 1_641_306,
    returneePopulation: 61_334,
    prri: 52,
    tier: 'TENSE',
    sectarianAnxiety: 35,
    securityEfficacy: 55,
    totalCapitalUSD: 60_100_000_000,
    unrepairedDamageUSD: 30_860_000_000,
    reconstructionScore: 0.48,
    dailyBlackoutHours: 20,
    activeHospitalsPct: 38,
    totalArableHectares: 450_000,
    mineSaturationPct: 65,
    skilledLaborCount: 45_000,
    connectedGovernorateIds: ['idlib', 'hama', 'raqqa'],
    strategicProject: {
      id: 'proj_aleppo_power',
      governorateId: 'aleppo',
      titleAr: 'تأهيل عنفات محطة حلب ومحولات الشيخ نجار الصناعية',
      issueDescriptionAr: 'انقطاع الكهرباء لنحو 20 ساعة يومياً وركام المحولات يعطل 140 منشأة نسيجية بالشيخ نجار ويهدد بهجرة المصنعين.',
      solutionDescriptionAr: 'استيراد قطع صيانة العنفات وتأهيل محولات الضغط العالي بالتعاون مع غرف الصناعة والقطاع الخاص.',
      costUSD: 75_000_000,
      costSYP: 500_000_000_000,
      costPoliticalCapital: 0,
      isExecuted: false,
      effectDescriptionAr: 'خفض ساعات التقنين بمقدار 8 ساعات، خفض مؤشر الشغب بـ 24 نقطة، وإصلاح 800 مليون دولار من الأضرار واستقطاب 25 ألف مهني.',
      prriDelta: -24,
      damageRepairedUSD: 800_000_000,
      blackoutHoursDelta: -8,
      mineClearancePct: 0,
      skilledLaborBonus: 25_000,
    },
  },
  idlib: {
    id: 'idlib',
    nameAr: 'إدلب',
    archetype: 'revolution_hub',
    hexQ: -1,
    hexR: -1,
    population: 3_104_168,
    hostPopulation: 963_984,
    idpPopulation: 2_106_929,
    returneePopulation: 33_255,
    prri: 48,
    tier: 'TENSE',
    sectarianAnxiety: 20,
    securityEfficacy: 65,
    totalCapitalUSD: 10_140_000_000,
    unrepairedDamageUSD: 5_960_000_000,
    reconstructionScore: 0.41,
    dailyBlackoutHours: 17,
    activeHospitalsPct: 45,
    totalArableHectares: 320_000,
    mineSaturationPct: 45,
    skilledLaborCount: 22_000,
    connectedGovernorateIds: ['aleppo', 'hama', 'latakia'],
    strategicProject: {
      id: 'proj_idlib_olive_corridor',
      governorateId: 'idlib',
      titleAr: 'كونسورتيوم تصدير الزيتون وتفكيك القنابل العنقودية',
      issueDescriptionAr: 'استيعاب 2.1 مليون نازح مع انتشار الذخائر العنقودية غير المنفجرة في بساتين سراقب ومعرة النعمان وكساد زيت الزيتون.',
      solutionDescriptionAr: 'تأسيس ائتلاف تسويق وتصدير زيت الزيتون وإطلاق فرق متخصصة لتفكيك القنابل العنقودية في الأراضي الزراعية.',
      costUSD: 20_000_000,
      costSYP: 300_000_000_000,
      costPoliticalCapital: 5,
      isExecuted: false,
      effectDescriptionAr: 'تطهير 15% من الذخائر العنقودية، خفض مؤشر الشغب بـ 15 نقطة، وتأمين مداخيل لـ 120 ألف أسرة مزارعة.',
      prriDelta: -15,
      damageRepairedUSD: 250_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 15,
      skilledLaborBonus: 5_000,
    },
  },
  latakia: {
    id: 'latakia',
    nameAr: 'اللاذقية',
    archetype: 'coastal_enclave',
    hexQ: -2,
    hexR: 0,
    population: 1_296_899,
    hostPopulation: 847_983,
    idpPopulation: 447_336,
    returneePopulation: 1_580,
    prri: 36,
    tier: 'CALM',
    sectarianAnxiety: 68,
    securityEfficacy: 60,
    totalCapitalUSD: 14_000_000_000,
    unrepairedDamageUSD: 1_430_000_000,
    reconstructionScore: 0.89,
    dailyBlackoutHours: 14,
    activeHospitalsPct: 75,
    totalArableHectares: 120_000,
    mineSaturationPct: 8,
    skilledLaborCount: 38_000,
    connectedGovernorateIds: ['idlib', 'tartus', 'homs'],
    strategicProject: {
      id: 'proj_latakia_port_modernization',
      governorateId: 'latakia',
      titleAr: 'أتمتة جمارك المرفأ وتأمين الاستقرار الوظيفي للكوادر',
      issueDescriptionAr: 'قلق موظفي الدولة الساحليين من الإقصاء الإداري، مع تفشي التهرب الجمركي وثغرات التهريب بأرصفة الحاويات.',
      solutionDescriptionAr: 'تركيب ماسحات إلكترونية شعاعية حديثة بميناء اللاذقية وتقديم ضمانات أمان وظيفي للأطباء والمعلمين وعمال الموانئ.',
      costUSD: 15_000_000,
      costSYP: 250_000_000_000,
      costPoliticalCapital: 10,
      isExecuted: false,
      effectDescriptionAr: 'خفض القلق الطائفي بـ 25 نقطة، خفض الشغب بـ 12 نقطة، ورفع كفاءة التدفقات السلعية والرسوم المرفئية بالدولار.',
      prriDelta: -12,
      damageRepairedUSD: 100_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 4,
      sectarianAnxietyDelta: -25,
      skilledLaborBonus: 8_000,
    },
  },
  tartus: {
    id: 'tartus',
    nameAr: 'طرطوس',
    archetype: 'coastal_enclave',
    hexQ: -2,
    hexR: 1,
    population: 939_889,
    hostPopulation: 767_539,
    idpPopulation: 171_149,
    returneePopulation: 1_201,
    prri: 32,
    tier: 'CALM',
    sectarianAnxiety: 64,
    securityEfficacy: 62,
    totalCapitalUSD: 8_500_000_000,
    unrepairedDamageUSD: 383_000_000,
    reconstructionScore: 0.95,
    dailyBlackoutHours: 12,
    activeHospitalsPct: 82,
    totalArableHectares: 95_000,
    mineSaturationPct: 2,
    skilledLaborCount: 30_000,
    connectedGovernorateIds: ['latakia', 'homs'],
    strategicProject: {
      id: 'proj_tartus_citrus_export',
      governorateId: 'tartus',
      titleAr: 'خط شحن الحمضيات المبرد وإعادة التدقيق المرفئي',
      issueDescriptionAr: 'كساد ملايين أطنان الحمضيات الساحلية وتدني العوائد السيادية المرفئية نتيجة قيود التعاقدات البحرية السابقة.',
      solutionDescriptionAr: 'إطلاق خط شحن حاويات مبردة مدعوم للموانئ العربية وإعادة تدقيق رسوم تشغيل رصيف الحاويات لزيادة حصة الخزينة.',
      costUSD: 10_000_000,
      costSYP: 200_000_000_000,
      costPoliticalCapital: 10,
      isExecuted: false,
      effectDescriptionAr: 'تأمين تصريف إنتاج 60 ألف مزارع، خفض القلق بـ 15 نقطة، ورفد الخزينة بالسيولة الصعبة.',
      prriDelta: -10,
      damageRepairedUSD: 50_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 1,
      sectarianAnxietyDelta: -15,
      skilledLaborBonus: 5_000,
    },
  },
  hama: {
    id: 'hama',
    nameAr: 'حماة',
    archetype: 'revolution_hub',
    hexQ: -1,
    hexR: 0,
    population: 1_522_898,
    hostPopulation: 1_302_717,
    idpPopulation: 212_582,
    returneePopulation: 7_599,
    prri: 46,
    tier: 'TENSE',
    sectarianAnxiety: 48,
    securityEfficacy: 52,
    totalCapitalUSD: 14_500_000_000,
    unrepairedDamageUSD: 7_470_000_000,
    reconstructionScore: 0.48,
    dailyBlackoutHours: 18,
    activeHospitalsPct: 42,
    totalArableHectares: 380_000,
    mineSaturationPct: 60,
    skilledLaborCount: 20_000,
    connectedGovernorateIds: ['aleppo', 'idlib', 'homs', 'raqqa'],
    strategicProject: {
      id: 'proj_hama_pastures_ghab',
      governorateId: 'hama',
      titleAr: 'تطهير مراعي البادية وتأهيل قنوات ري سهل الغاب',
      issueDescriptionAr: '60% تلوث بالألغام بالريف الشرقي يفتك برعاة الماشية، مع انسداد قنوات الري وتراجع إنتاج سكر وأعلاف سهل الغاب.',
      solutionDescriptionAr: 'تسيير كاسحات ألغام لفتح مسارات رعي آمنة لقطعان الأغنام وتطهير قنوات حوض العاصي وسهل الغاب.',
      costUSD: 25_000_000,
      costSYP: 350_000_000_000,
      costPoliticalCapital: 5,
      isExecuted: false,
      effectDescriptionAr: 'تطهير 20% من الألغام، خفض مؤشر الشغب بـ 16 نقطة، وحماية 300 ألف رأس من أغنام العواس السورية.',
      prriDelta: -16,
      damageRepairedUSD: 300_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 20,
      skilledLaborBonus: 4_000,
    },
  },
  homs: {
    id: 'homs',
    nameAr: 'حمص',
    archetype: 'revolution_hub',
    hexQ: -1,
    hexR: 1,
    population: 1_500_351,
    hostPopulation: 1_204_579,
    idpPopulation: 290_269,
    returneePopulation: 5_503,
    prri: 49,
    tier: 'TENSE',
    sectarianAnxiety: 58,
    securityEfficacy: 55,
    totalCapitalUSD: 22_000_000_000,
    unrepairedDamageUSD: 10_830_000_000,
    reconstructionScore: 0.50,
    dailyBlackoutHours: 18,
    activeHospitalsPct: 40,
    totalArableHectares: 340_000,
    mineSaturationPct: 40,
    skilledLaborCount: 32_000,
    connectedGovernorateIds: ['hama', 'latakia', 'tartus', 'rif_dimashq', 'deir_ez_zor'],
    strategicProject: {
      id: 'proj_homs_refinery_corridor',
      governorateId: 'homs',
      titleAr: 'عمرة مصفاة حمص وتأمين محور الترانزيت M5',
      issueDescriptionAr: 'تراجع كفاءة مصفاة النفط، واحتكاكات أمنية على مسارات شاحنات الترانزيت والوقود، وتوتر مجتمعي بالأحياء القديمة.',
      solutionDescriptionAr: 'صيانة كتل التقطير والتكسير في مصفاة حمص ونشر دوريات أمنية منضبطة لحماية مسار الترانزيت الدولي M5.',
      costUSD: 50_000_000,
      costSYP: 450_000_000_000,
      costPoliticalCapital: 5,
      isExecuted: false,
      effectDescriptionAr: 'توفير المشتقات النفطية، خفض الظلام بـ 4 ساعات، خفض الشغب بـ 18 نقطة، وخفض القلق الطائفي بـ 15 نقطة.',
      prriDelta: -18,
      damageRepairedUSD: 450_000_000,
      blackoutHoursDelta: -4,
      mineClearancePct: 10,
      sectarianAnxietyDelta: -15,
      skilledLaborBonus: 6_000,
    },
  },
  rif_dimashq: {
    id: 'rif_dimashq',
    nameAr: 'ريف دمشق',
    archetype: 'revolution_hub',
    hexQ: -1,
    hexR: 2,
    population: 3_386_173,
    hostPopulation: 2_389_737,
    idpPopulation: 985_957,
    returneePopulation: 10_479,
    prri: 54,
    tier: 'TENSE',
    sectarianAnxiety: 42,
    securityEfficacy: 50,
    totalCapitalUSD: 45_000_000_000,
    unrepairedDamageUSD: 22_300_000_000,
    reconstructionScore: 0.50,
    dailyBlackoutHours: 20,
    activeHospitalsPct: 35,
    totalArableHectares: 260_000,
    mineSaturationPct: 70,
    skilledLaborCount: 35_000,
    connectedGovernorateIds: ['homs', 'damascus', 'daraa', 'as_suwayda', 'quneitra'],
    strategicProject: {
      id: 'proj_rif_dimashq_cadastre',
      governorateId: 'rif_dimashq',
      titleAr: 'المسح العقاري الرقمي وتطهير المسارات الزراعية بالغوطة',
      issueDescriptionAr: '70% تلوث بالذخائر في بساتين الغوطة وداريا مع بطء إزالة الأنقاض وشلل إعادة الإعمار السكني.',
      solutionDescriptionAr: 'تطبيق التوثيق العقاري الرقمي وفق المرسوم 16 ونشر كاسحات الألغام في المسارات الزراعية لحوض الغوطة.',
      costUSD: 35_000_000,
      costSYP: 600_000_000_000,
      costPoliticalCapital: 10,
      isExecuted: false,
      effectDescriptionAr: 'تطهير 20% من حقول الألغام، خفض مؤشر الشغب بـ 18 نقطة، وإتاحة 45 ألف هكتار زراعي للخضار والمحاصيل.',
      prriDelta: -18,
      damageRepairedUSD: 600_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 20,
      skilledLaborBonus: 8_000,
    },
  },
  damascus: {
    id: 'damascus',
    nameAr: 'مدينة دمشق',
    archetype: 'revolution_hub',
    hexQ: -2,
    hexR: 2,
    population: 1_812_911,
    hostPopulation: 1_221_462,
    idpPopulation: 589_880,
    returneePopulation: 1_569,
    prri: 40,
    tier: 'TENSE',
    sectarianAnxiety: 30,
    securityEfficacy: 78,
    totalCapitalUSD: 48_000_000_000,
    unrepairedDamageUSD: 5_530_000_000,
    reconstructionScore: 0.88,
    dailyBlackoutHours: 13,
    activeHospitalsPct: 72,
    totalArableHectares: 15_000,
    mineSaturationPct: 5,
    skilledLaborCount: 85_000,
    connectedGovernorateIds: ['rif_dimashq'],
    strategicProject: {
      id: 'proj_damascus_water_rents',
      governorateId: 'damascus',
      titleAr: 'تأهيل مضخات عين الفيجة وضبط سقوف الإيجارات السكنية',
      issueDescriptionAr: 'شح مائي متكرر لحوض الفيجة، وتضخم إيجارات المساكن بنسبة 45% نتيجة تدفق الكوادر المهنية والنازحين للعاصمة.',
      solutionDescriptionAr: 'تجديد منظومات الضخ الهيدروليكية لنبع الفيجة وتحديد سقوف قانونية لإيجارات موظفي القطاع الحكومي والخدمي.',
      costUSD: 15_000_000,
      costSYP: 400_000_000_000,
      costPoliticalCapital: 15,
      isExecuted: false,
      effectDescriptionAr: 'استقرار ضخ مياه الشرب، خفض مؤشر الشغب بـ 14 نقطة، وتخفيف أعباء المعيشة عن الموظفين والكوادر.',
      prriDelta: -14,
      damageRepairedUSD: 200_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 3,
      skilledLaborBonus: 10_000,
    },
  },
  quneitra: {
    id: 'quneitra',
    nameAr: 'القنيطرة',
    archetype: 'autonomous_frontier',
    hexQ: -4,
    hexR: 3,
    population: 149_326,
    hostPopulation: 141_834,
    idpPopulation: 3_373,
    returneePopulation: 4_119,
    prri: 45,
    tier: 'TENSE',
    sectarianAnxiety: 25,
    securityEfficacy: 45,
    totalCapitalUSD: 950_000_000,
    unrepairedDamageUSD: 499_000_000,
    reconstructionScore: 0.47,
    dailyBlackoutHours: 19,
    activeHospitalsPct: 30,
    totalArableHectares: 45_000,
    mineSaturationPct: 55,
    skilledLaborCount: 2_500,
    golanTensionIndex: 45,
    connectedGovernorateIds: ['rif_dimashq', 'daraa'],
    strategicProject: {
      id: 'proj_quneitra_undof_wells',
      governorateId: 'quneitra',
      titleAr: 'تطهير حزام الجولان وإعادة حفر آبار خط الهدنة',
      issueDescriptionAr: '55% تلوث بالألغام على خط الهدنة، وتجريف الآبار الزراعية، مع مخاطر توغلات إسرائيلية في الحزام الأمني.',
      solutionDescriptionAr: 'نشر كاسحات ألغام بالتعاون مع قوة الأندوف (UNDOF) وإعادة حفر آبار المياه الجوفية لكافة قرى خط الهدنة.',
      costUSD: 12_000_000,
      costSYP: 150_000_000_000,
      costPoliticalCapital: 10,
      isExecuted: false,
      effectDescriptionAr: 'تطهير 25% من الألغام الحدودية، خفض توتر الجولان بـ 20 نقطة، خفض الشغب بـ 15 نقطة، وعودة آمنة للمزارعين.',
      prriDelta: -15,
      damageRepairedUSD: 120_000_000,
      blackoutHoursDelta: -3,
      mineClearancePct: 25,
      golanTensionDelta: -20,
      skilledLaborBonus: 1_500,
    },
  },
  daraa: {
    id: 'daraa',
    nameAr: 'درعا',
    archetype: 'revolution_hub',
    hexQ: -3,
    hexR: 3,
    population: 1_075_114,
    hostPopulation: 1_000_049,
    idpPopulation: 66_868,
    returneePopulation: 8_197,
    prri: 50,
    tier: 'TENSE',
    sectarianAnxiety: 30,
    securityEfficacy: 48,
    totalCapitalUSD: 8_500_000_000,
    unrepairedDamageUSD: 4_300_000_000,
    reconstructionScore: 0.49,
    dailyBlackoutHours: 18,
    activeHospitalsPct: 44,
    totalArableHectares: 210_000,
    mineSaturationPct: 30,
    skilledLaborCount: 16_000,
    golanTensionIndex: 45,
    daraaDefianceIndex: 54,
    nassibRevenueCapturePct: 32,
    connectedGovernorateIds: ['rif_dimashq', 'quneitra', 'as_suwayda'],
    strategicProject: {
      id: 'proj_daraa_nassib_border',
      governorateId: 'daraa',
      titleAr: 'حوسبة معبر نصيب وتشكيل حرس حدود حوران المحلي',
      issueDescriptionAr: 'ضياع رسوم معبر نصيب لصالح شبكات التهريب وتصاعد التوتر العسكري على شريط الجولان وحوض اليرموك.',
      solutionDescriptionAr: 'تركيب بوابات جمركية رقمية بمعبر نصيب واستيعاب مقاتلي حوران المحليين ضمن قوة أمن حدود نظامية.',
      costUSD: 20_000_000,
      costSYP: 250_000_000_000,
      costPoliticalCapital: 15,
      isExecuted: false,
      effectDescriptionAr: 'رفع تحصيل نصيب إلى 80%، خفض تمرد درعا بـ 25 نقطة، خفض الشغب بـ 18 نقطة، وتأمين التبادل مع الأردن.',
      prriDelta: -18,
      damageRepairedUSD: 200_000_000,
      blackoutHoursDelta: -2,
      mineClearancePct: 15,
      revenueCaptureBoost: 48,
      skilledLaborBonus: 4_000,
    },
  },
  as_suwayda: {
    id: 'as_suwayda',
    nameAr: 'السويداء',
    archetype: 'autonomous_frontier',
    hexQ: -2,
    hexR: 3,
    population: 446_493,
    hostPopulation: 372_692,
    idpPopulation: 70_842,
    returneePopulation: 2_959,
    prri: 42,
    tier: 'TENSE',
    sectarianAnxiety: 60,
    securityEfficacy: 40,
    totalCapitalUSD: 4_200_000_000,
    unrepairedDamageUSD: 464_000_000,
    reconstructionScore: 0.88,
    dailyBlackoutHours: 16,
    activeHospitalsPct: 62,
    totalArableHectares: 140_000,
    mineSaturationPct: 5,
    skilledLaborCount: 12_000,
    suwaydaIntegrationIndex: 8,
    suwaydaSecessionProb: 24,
    tribalRageIndex: 74,
    connectedGovernorateIds: ['rif_dimashq', 'daraa'],
    strategicProject: {
      id: 'proj_suwayda_power_lajat',
      governorateId: 'as_suwayda',
      titleAr: 'محطة تحويل كهرباء الجبل وميثاق صلح اللجاة',
      issueDescriptionAr: 'انقطاعات الكهرباء تدفع الفعاليات لمقاطعة الضرائب المركزية، مع توتر مسلح متجدد مع العشائر في صخور اللجاة.',
      solutionDescriptionAr: 'إنشاء محطة تحويل 66 ك.ف لتغذية قرى الجبل، ورعاية ميثاق شرف عشائري-درزي لضمان أمن طريق دمشق-السويداء.',
      costUSD: 15_000_000,
      costSYP: 200_000_000_000,
      costPoliticalCapital: 20,
      isExecuted: false,
      effectDescriptionAr: 'رفع اندماج السويداء بـ 40%، خفض احتمال الانفصال إلى 4%، إنهاء حصار الطرق، وخفض مؤشر الشغب بـ 20 نقطة.',
      prriDelta: -20,
      damageRepairedUSD: 120_000_000,
      blackoutHoursDelta: -4,
      mineClearancePct: 3,
      suwaydaIntegrationBonus: 40,
      tribalRageDelta: -35,
      skilledLaborBonus: 3_000,
    },
  },
  raqqa: {
    id: 'raqqa',
    nameAr: 'الرقة',
    archetype: 'autonomous_frontier',
    hexQ: 1,
    hexR: -2,
    population: 847_132,
    hostPopulation: 678_895,
    idpPopulation: 152_955,
    returneePopulation: 15_282,
    prri: 47,
    tier: 'TENSE',
    sectarianAnxiety: 35,
    securityEfficacy: 50,
    totalCapitalUSD: 13_500_000_000,
    unrepairedDamageUSD: 6_840_000_000,
    reconstructionScore: 0.49,
    dailyBlackoutHours: 17,
    activeHospitalsPct: 36,
    totalArableHectares: 480_000,
    mineSaturationPct: 65,
    skilledLaborCount: 14_000,
    connectedGovernorateIds: ['aleppo', 'hama', 'deir_ez_zor', 'hasakeh'],
    strategicProject: {
      id: 'proj_raqqa_tabqa_dam',
      governorateId: 'raqqa',
      titleAr: 'صيانة عنفات سد الطبقة ونزع تفخيخ أحياء المدينة',
      issueDescriptionAr: 'توقف عنفات التوليد الكهرومائي بسد الطبقة، مع كثافة عبوات ناسفة ومخلفات بمحيط المنشآت الحضرية (65% تلوث).',
      solutionDescriptionAr: 'استيراد محاور دوارة ومحولات لسد الطبقة، وإرسال فرق روبوتية متخصصة لتفكيك الأفخاخ في مركز الرقة.',
      costUSD: 35_000_000,
      costSYP: 300_000_000_000,
      costPoliticalCapital: 5,
      isExecuted: false,
      effectDescriptionAr: 'توليد 250 ميغاواط كهرباء إضافية، خفض ساعات التقنين بـ 5 ساعات، وتطهير 20% من مخلفات الألغام والعبوات.',
      prriDelta: -20,
      damageRepairedUSD: 500_000_000,
      blackoutHoursDelta: -5,
      mineClearancePct: 20,
      skilledLaborBonus: 4_000,
    },
  },
  hasakeh: {
    id: 'hasakeh',
    nameAr: 'الحسكة',
    archetype: 'autonomous_frontier',
    hexQ: 2,
    hexR: -2,
    population: 1_431_461,
    hostPopulation: 1_078_796,
    idpPopulation: 342_701,
    returneePopulation: 9_964,
    prri: 44,
    tier: 'TENSE',
    sectarianAnxiety: 52,
    securityEfficacy: 54,
    totalCapitalUSD: 16_000_000_000,
    unrepairedDamageUSD: 5_580_000_000,
    reconstructionScore: 0.65,
    dailyBlackoutHours: 16,
    activeHospitalsPct: 58,
    totalArableHectares: 850_000,
    mineSaturationPct: 35,
    skilledLaborCount: 22_000,
    connectedGovernorateIds: ['raqqa', 'deir_ez_zor'],
    strategicProject: {
      id: 'proj_hasakeh_wheat_suwaydiya',
      governorateId: 'hasakeh',
      titleAr: 'التسوية الاقتصادية للقمح وتشغيل محطة السويدية الغازية',
      issueDescriptionAr: 'ازدواجية الإدارة مع الإدارة الذاتية، وتنازع تسعير صوامع الحبوب، وتذبذب توريد الغاز لمحطة السويدية الكهربائية.',
      solutionDescriptionAr: 'إبرام تسوية مالية مجزية لشراء كامل محصول القمح القاسي، وبروتوكول فني لتشغيل عنفات غاز رميلان والسويدية.',
      costUSD: 30_000_000,
      costSYP: 500_000_000_000,
      costPoliticalCapital: 15,
      isExecuted: false,
      effectDescriptionAr: 'تأمين 600 ألف طن قمح للاستهلاك الوطني، خفض الشغب بـ 18 نقطة، وخفض القلق القومي والمناطقي بـ 20 نقطة.',
      prriDelta: -18,
      damageRepairedUSD: 350_000_000,
      blackoutHoursDelta: -4,
      mineClearancePct: 10,
      sectarianAnxietyDelta: -20,
      skilledLaborBonus: 5_000,
    },
  },
  deir_ez_zor: {
    id: 'deir_ez_zor',
    nameAr: 'دير الزور',
    archetype: 'autonomous_frontier',
    hexQ: 2,
    hexR: 0,
    population: 1_200_181,
    hostPopulation: 1_024_484,
    idpPopulation: 166_041,
    returneePopulation: 9_656,
    prri: 51,
    tier: 'TENSE',
    sectarianAnxiety: 38,
    securityEfficacy: 46,
    totalCapitalUSD: 11_200_000_000,
    unrepairedDamageUSD: 5_760_000_000,
    reconstructionScore: 0.48,
    dailyBlackoutHours: 19,
    activeHospitalsPct: 28,
    totalArableHectares: 310_000,
    mineSaturationPct: 75,
    skilledLaborCount: 11_000,
    connectedGovernorateIds: ['homs', 'raqqa', 'hasakeh'],
    strategicProject: {
      id: 'proj_deir_ez_zor_tribal_pact',
      governorateId: 'deir_ez_zor',
      titleAr: 'الميثاق العشائري لحقول النفط وتطهير ضفاف الفرات',
      issueDescriptionAr: '75% تلوث بالألغام على ضفاف النهر، وتهديد العشائر بقطع خطوط نفط العمر وكونيكو حال عدم نيل حصة تنموية عادلة.',
      solutionDescriptionAr: 'تثبيت حصة 30% من عوائد حقول الفرات لبلديات المحافظة وتكثيف فرق الهندسة لتطهير حقول الحبوب بالميادين.',
      costUSD: 40_000_000,
      costSYP: 400_000_000_000,
      costPoliticalCapital: 15,
      isExecuted: false,
      effectDescriptionAr: 'تطهير 25% من الألغام، خفض احتقان العشائر بـ 40 نقطة، خفض الشغب بـ 26 نقطة، وضمان تدفق 45 ألف برميل نفط.',
      prriDelta: -26,
      damageRepairedUSD: 400_000_000,
      blackoutHoursDelta: -3,
      mineClearancePct: 25,
      tribalRageDelta: -40,
      skilledLaborBonus: 4_000,
    },
  },
};

// The Executive Ministries Baseline Profile (March 2025 Restructuring & May 2026 Reshuffle)
export const BASELINE_MINISTRIES: Record<string, MinistryProfile> = {
  energy: {
    id: 'energy',
    nameAr: 'وزارة الطاقة',
    ministerNameAr: 'محمد البشير',
    isOpposition: false,
    competence: 45,
    corruption: 42,
    allocatedBudgetSYP: 750_000_000_000,
    allocatedCapExUSD: 75_000_000,
  },
  economy: {
    id: 'economy',
    nameAr: 'وزارة الاقتصاد والصناعة',
    ministerNameAr: 'د. نضال الشعار',
    isOpposition: false,
    competence: 52,
    corruption: 40,
    allocatedBudgetSYP: 600_000_000_000,
    allocatedCapExUSD: 30_000_000,
  },
  disaster: {
    id: 'disaster',
    nameAr: 'وزارة الطوارئ والكوارث',
    ministerNameAr: 'رائد الصالح',
    isOpposition: false,
    competence: 68,
    corruption: 20,
    allocatedBudgetSYP: 400_000_000_000,
    allocatedCapExUSD: 35_000_000,
  },
  local_admin: {
    id: 'local_admin',
    nameAr: 'وزارة الإدارة المحلية والبيئة',
    ministerNameAr: 'محمد عنجراني',
    isOpposition: false,
    competence: 42,
    corruption: 48,
    allocatedBudgetSYP: 600_000_000_000,
    allocatedCapExUSD: 15_000_000,
  },
  housing: {
    id: 'housing',
    nameAr: 'وزارة الأشغال العامة والإسكان',
    ministerNameAr: 'مصطفى عبد الرزاق',
    isOpposition: false,
    competence: 46,
    corruption: 50,
    allocatedBudgetSYP: 500_000_000_000,
    allocatedCapExUSD: 35_000_000,
  },
  finance: {
    id: 'finance',
    nameAr: 'وزارة المالية',
    ministerNameAr: 'محمد يسر برنية',
    isOpposition: false,
    competence: 58,
    corruption: 36,
    allocatedBudgetSYP: 750_000_000_000,
    allocatedCapExUSD: 15_000_000,
  },
  agriculture: {
    id: 'agriculture',
    nameAr: 'وزارة الزراعة والإصلاح الزراعي',
    ministerNameAr: 'باسل حافظ السويدان (المرسوم 101)',
    isOpposition: false,
    competence: 48,
    corruption: 40,
    allocatedBudgetSYP: 450_000_000_000,
    allocatedCapExUSD: 20_000_000,
  },
  media: {
    id: 'media',
    nameAr: 'وزارة الإعلام',
    ministerNameAr: 'خالد فواز زعرور (المرسوم 100)',
    isOpposition: false,
    competence: 50,
    corruption: 32,
    allocatedBudgetSYP: 150_000_000_000,
    allocatedCapExUSD: 5_000_000,
  },
};

// Sovereign Bodies & Specialized Presidential Commissions (Direct Presidential System)
export const BASELINE_COMMISSIONS: Record<string, CommissionState> = {
  presidential_secretariat: {
    id: 'presidential_secretariat',
    nameAr: 'الأمانة العامة لرئاسة الجمهورية',
    leaderNameAr: 'عبد الرحمن الأعمى (المرسوم 98)',
    mandateAr: 'التنسيق الحكومي والإشراف المباشر على تنفيذ التوجيهات الرئاسية',
    isActive: true,
    progress: 25,
  },
  inspection: {
    id: 'inspection',
    nameAr: 'الهيئة المركزية للرقابة والتفتيش',
    leaderNameAr: 'عامر نامس العلي',
    mandateAr: 'مكافحة الفساد والرقابة المالية والإدارية وتدقيق العقود والمناقصات',
    isActive: true,
    progress: 20,
  },
  customs_ports: {
    id: 'customs_ports',
    nameAr: 'الهيئة العامة للمنافذ والجمارك والموانئ',
    leaderNameAr: 'قتيبة أحمد بدوي (المعاون: خالد البراد / الموانئ: أحمد مصطفى)',
    mandateAr: 'إدارة وتأهيل المعابر الحدودية وتحديث المنظومة الجمركية والموانئ',
    isActive: true,
    progress: 18,
  },
  service_extension: {
    id: 'service_extension',
    nameAr: 'لجنة تمديد الخدمة والوظائف العامة',
    leaderNameAr: 'محمد حسان سكاف (وزير التنمية الإدارية)',
    mandateAr: 'وضع معايير الجدارة واختيار وتمديد القيادات والمديرين العامين',
    isActive: true,
    progress: 15,
  },
  transitional_justice: {
    id: 'transitional_justice',
    nameAr: 'هيئة العدالة الانتقالية وفحص المظالم (المرسوم 20)',
    leaderNameAr: 'مظهر الويس (وزير العدل)',
    mandateAr: 'معالجة تركة الحرب وحفظ السلم الأهلي وإنفاذ سيادة القانون',
    isActive: true,
    progress: 12,
  },
};

// Confiscated Assets & Oligarch Monopolies Pipeline (Decree 13 / Illicit Enrichment)
export const BASELINE_CONFISCATED_ASSETS: ConfiscatedAsset[] = [
  {
    id: 'syriatel_mtn',
    titleAr: 'شبكات الاتصالات الخلوية (سيريتل و MTN سوريا)',
    category: 'TELECOM',
    ownerNameAr: 'رامي مخلوف والشبكات المالية التابعة',
    valuationUSD: 650_000_000,
    valuationSYP: 10_500_000_000_000,
    settlementYieldUSD: 350_000_000,
    settlementYieldSYP: 4_000_000_000_000,
    liquidationYieldUSD: 520_000_000,
    soeVenueSYPPerTurn: 600_000_000_000,
    status: 'PENDING',
  },
  {
    id: 'hamsho_steel',
    titleAr: 'مجمعات صهر ودرفلة الحديد وخردة المعادن بعدرا',
    category: 'INDUSTRY',
    ownerNameAr: 'محمد حمشو ومجموعة شركاته الصناعية',
    valuationUSD: 280_000_000,
    valuationSYP: 4_500_000_000_000,
    settlementYieldUSD: 150_000_000,
    settlementYieldSYP: 1_800_000_000_000,
    liquidationYieldUSD: 220_000_000,
    soeVenueSYPPerTurn: 280_000_000_000,
    status: 'PENDING',
  },
  {
    id: 'marota_city',
    titleAr: 'أبراج وأراضي مشروع ماروتا سيتي وشركة شام القابضة',
    category: 'REAL_ESTATE',
    ownerNameAr: 'تحالف أوليغارشيا التطوير العقاري المصادرة',
    valuationUSD: 400_000_000,
    valuationSYP: 6_400_000_000_000,
    settlementYieldUSD: 200_000_000,
    settlementYieldSYP: 2_500_000_000_000,
    liquidationYieldUSD: 320_000_000,
    soeVenueSYPPerTurn: 350_000_000_000,
    status: 'PENDING',
  },
  {
    id: 'four_seasons_damascus',
    titleAr: 'حصة الـ 51% في فندق فور سيزونز وسلسلة الأصول الفندقية',
    category: 'HOSPITALITY',
    ownerNameAr: 'سامر فوز وشبكات التوريد الغذائي والفندقي',
    valuationUSD: 140_000_000,
    valuationSYP: 2_200_000_000_000,
    settlementYieldUSD: 75_000_000,
    settlementYieldSYP: 900_000_000_000,
    liquidationYieldUSD: 110_000_000,
    soeVenueSYPPerTurn: 150_000_000_000,
    status: 'PENDING',
  },
];

// Tri-Bloc International Financing Packages
export const BASELINE_FOREIGN_LOANS: ForeignLoanPackage[] = [
  {
    id: 'loan_imf_wb',
    bloc: 'WESTERN_IFI',
    titleAr: 'تسهيل التعافي الهيكلي من صندوق النقد والبنك الدولي',
    lenderAr: 'المؤسسات المالية الدولية والغربية',
    disbursementUSD: 500_000_000,
    interestRatePct: 2.5,
    politicalCapitalCost: 20,
    concessionSummaryAr: 'تدقيق دولي كامل للشفافية، مكافحة الفساد، وخفض التوظيف الحكومي',
    isSigned: false,
  },
  {
    id: 'loan_gulf_swf',
    bloc: 'GULF_SWF',
    titleAr: 'وديعة الاستقرار النقدي وصناديق الاستثمار الخليجية',
    lenderAr: 'صناديق الثروة السيادية الخليجية (الإمارات والسعودية)',
    disbursementUSD: 400_000_000,
    interestRatePct: 3.5,
    politicalCapitalCost: 10,
    concessionSummaryAr: 'تطبيع سياسي ودبلوماسي وتخصيص حقوق استثمار في العقارات والواجهات البحرية',
    isSigned: false,
  },
  {
    id: 'loan_eastern_credit',
    bloc: 'EASTERN_POWERS',
    titleAr: 'خط الائتمان الاستثماري للطاقة ومحطات النقل الشرقي',
    lenderAr: 'الكونسورتيوم الصيني الروسي للبنية التحتية',
    disbursementUSD: 350_000_000,
    interestRatePct: 4.0,
    politicalCapitalCost: 15,
    concessionSummaryAr: 'عقود امتياز لتوريد التوربينات وربط عقود المقايضة التعدينية طويلة الأجل',
    isSigned: false,
  },
];

// Emergency Concessionary Mortgaging of Sovereign Assets
export const BASELINE_SOVEREIGN_MORTGAGES: SovereignMortgageOption[] = [
  {
    id: 'mortgage_tartus_port',
    titleAr: 'عقد تشغيل وامتياز محطة حاويات مرفأ طرطوس التجاري',
    assetNameAr: 'أرصفة ورافعات مرفأ طرطوس الدولي',
    concessionDurationYears: 49,
    immediateCashUSD: 450_000_000,
    turnRevenueLossUSD: 40_000_000,
    sovereigntyPenaltyAr: 'خسارة السيادة البحرية وحرمان الموازنة من الرسوم الجمركية الترانزيتية المباشرة',
    isMortgaged: false,
  },
  {
    id: 'mortgage_khneifis_phosphate',
    titleAr: 'حقوق استخراج ونقل خامات فوسفات خنيفيس والشرقية',
    assetNameAr: 'مناجم الفوسفات في بادية تدمر',
    concessionDurationYears: 30,
    immediateCashUSD: 300_000_000,
    turnRevenueLossUSD: 60_000_000,
    sovereigntyPenaltyAr: 'رهن الاحتياطي التعديني الاستراتيجي وحرمان الدولة من عوائد التصدير الدولارية',
    isMortgaged: false,
  },
];
